Repository 4-mul-meong/frontend, pull requests merged in 2024-11, with the labels that each got.

#5 👷 Chore(config): add auto-assign
  .github/auto_assign.yml
Labels: 👷 chore

#12 [🔀 FE] 🎨 Refactor: add path-alias & index.ts
  apps/web/src/app/(feed)/layout.tsx
  apps/web/src/app/(feed)/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/not-found.tsx
  apps/web/src/components/common/icons/@type.d.ts
  apps/web/src/components/common/icons/Globe.tsx
  apps/web/src/components/common/icons/Home.tsx
  apps/web/src/components/common/icons/Kitty.tsx
  apps/web/src/components/common/icons/Logo.tsx
  apps/web/src/components/common/icons/Menu.tsx
  apps/web/src/components/common/icons/Mypage.tsx
  apps/web/src/components/common/icons/Notification.tsx
  apps/web/src/components/common/icons/Post.tsx
  apps/web/src/components/common/icons/Search.tsx
  apps/web/src/components/common/icons/Shorts.tsx
  apps/web/src/components/common/icons/index.ts
  apps/web/src/components/common/molecules/index.ts
  apps/web/src/components/common/organisms/CommonGbnb.tsx
  apps/web/src/components/common/organisms/index.ts
  apps/web/src/components/feed-tab/atoms/ChatButton.tsx
  apps/web/src/components/feed-tab/atoms/GlobalButton.tsx
  apps/web/src/components/feed-tab/atoms/LnbMenuButton.tsx
  apps/web/src/components/feed-tab/atoms/NotificationButton.tsx
  apps/web/src/components/feed-tab/atoms/index.ts
  apps/web/src/components/feed-tab/organisms/FeedTabHeader.tsx
  apps/web/src/components/feed-tab/organisms/index.ts
  apps/web/tsconfig.json
Labels: ✨ enhancement

#13 [🔀 FE] Feed component 구현
  apps/web/db.json
  apps/web/package.json
  apps/web/public/dummies/medias/media-001.png
  apps/web/public/dummies/medias/media-002.png
  apps/web/public/dummies/medias/media-003.png
  apps/web/public/dummies/medias/media-004.png
  apps/web/public/dummies/members/member-001.png
  apps/web/public/dummies/members/member-002.png
  apps/web/public/dummies/members/member-003.png
  apps/web/src/actions/feed/index.ts
  apps/web/src/app/(feed)/feeds/[feedUuid]/page.tsx
  apps/web/src/app/(feed)/page.tsx
  apps/web/src/app/globals.css
  apps/web/src/components/common/atoms/ButtonWithAuth.tsx
  apps/web/src/components/common/atoms/Fig.tsx
  apps/web/src/components/common/atoms/PostedAt.tsx
  apps/web/src/components/common/atoms/index.ts
  apps/web/src/components/common/atoms/withLink.tsx
  apps/web/src/components/common/icons/Comment.tsx
  apps/web/src/components/common/icons/Ellipsis.tsx
  apps/web/src/components/common/icons/Heart.tsx
  apps/web/src/components/common/icons/Save.tsx
  apps/web/src/components/common/icons/Share.tsx
  apps/web/src/components/common/icons/index.ts
  apps/web/src/components/feed-tab/templates/FeedList.tsx
  apps/web/src/components/feed/molecules/FeedButtonGroup.tsx
  apps/web/src/components/feed/molecules/FeedContent.tsx
  apps/web/src/components/feed/molecules/FeedHashtagList.tsx
  apps/web/src/components/feed/molecules/FeedHeader.tsx
  apps/web/src/components/feed/molecules/FeedMediaContainer.tsx
  apps/web/src/components/feed/molecules/index.ts
  apps/web/src/components/feed/organisms/Feed.tsx
  apps/web/src/components/profile/molecules/Profile.tsx
  apps/web/src/functions/utils/alertNotImplemented.ts
  apps/web/src/functions/utils/getProfileUrl.tsx
  apps/web/src/functions/utils/index.ts
  apps/web/src/types/common/dummy.ts
  apps/web/src/types/common/index.d.ts
  apps/web/src/types/contents/common.d.ts
  apps/web/src/types/contents/feed.d.ts
  apps/web/src/types/contents/index.d.ts
  apps/web/src/types/member/index.d.ts
  pnpm-lock.yaml
  turbo.json
Labels: 🐛 bug, ✨ enhancement, 👷 chore

#22 [🚑️ Frontend] 배포 및 실행 에러 Resolve
  .github/workflows/cicd.yml
  Dockerfile
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#30 [🚀 Frontend] Docker network 연결 및 env 파일 생성 로직 추가
  .github/workflows/cicd.yml
  Dockerfile
  apps/web/src/app/(feed)/feeds/[feedUuid]/page.tsx
  apps/web/src/app/(feed)/page.tsx
Labels: 👷 chore, 🚀 deploy

#43 [🔀 FE] comment-service에 세션 유저 정보 반영 및 member-read-service 연결
  apps/web/src/actions/comment-service/index.ts
  apps/web/src/actions/common/index.ts
  apps/web/src/actions/member-read-service/index.ts
  apps/web/src/actions/member-service/index.ts
  apps/web/src/app/(auth)/sign-out/page.tsx
  apps/web/src/components/comments/molecules/CommentInput.tsx
  apps/web/src/components/comments/organisms/Comment.tsx
  apps/web/src/components/common/molecules/QueryClientProvider.tsx
  apps/web/src/types/comment-service/index.d.ts
  apps/web/src/types/member/index.d.ts
Labels: ✨ enhancement

#46 [🔀 FE] utility-service server-action 구현
  apps/web/src/actions/utility-service/bookmarkService.ts
  apps/web/src/actions/utility-service/followService.ts
  apps/web/src/actions/utility-service/index.ts
  apps/web/src/actions/utility-service/likeService.ts
  apps/web/src/functions/utils/index.ts
  apps/web/src/functions/utils/toURLSearchParams.ts
  apps/web/src/types/common/index.d.ts
  apps/web/src/types/feed-service/index.d.ts
  apps/web/src/types/member/index.d.ts
  apps/web/src/types/shorts-service/index.d.ts
  apps/web/src/types/utility-service/bookmarkService.d.ts
  apps/web/src/types/utility-service/followService.d.ts
  apps/web/src/types/utility-service/index.d.ts
  apps/web/src/types/utility-service/likeService.d.ts
Labels: ✨ enhancement
